# Stage 1
# FROM node as build
# WORKDIR /app
# COPY package.json .
# RUN npm install
# COPY . .

# # Environment variables
# ARG REACT_APP_NAME
# ENV REACT_APP_NAME=$REACT_APP_NAME

# RUN npm run build

# Stage 2
# FROM nginx
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80

FROM nginx
COPY ./build /usr/share/nginx/html
EXPOSE 80