version: "3"
services:
  react-docker-app:
    image: react-docker-app-image-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/app/src:ro
      - ./public:/app/public:ro
    # environment:
    #   - REACT_APP_NAME=brandongs
    env_file:
      - ./.env.dev
